exports.MSG_user404 = "El usuario no existe"
exports.MSG_pass401 = "Password incorrecto"
exports.MSG_auth200 = "Auth ok"
exports.MSG_ERRORAUTH = "Ocurrio un error al autenticar"
exports.MSG_UNAUTHORIZED = "No tienes permitida esta acción"